version: '2'
services:
    jhipstersampleapp-app:
        image: jhipstersampleapp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://jhipstersampleapp-postgresql:5432/jHipsterSampleApp
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=jhipstersampleapp-elasticsearch:9300
        ports:
            - 8080:8080
    jhipstersampleapp-postgresql:
        extends:
            file: postgresql.yml
            service: jhipstersampleapp-postgresql
    jhipstersampleapp-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: jhipstersampleapp-elasticsearch
